const BD_NAME = "skd_dev"
const DB_URI = process.env.DB_URI

const CORS_ORIGINE = process.env.CORS_ORIGINE

const PORT = process.env.PORT

const CLOUDINARY_NAME = process.env.CLOUDINARY_NAME
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET
const CLOUDINARY_FOLDER_NAME = process.env.CLOUDINARY_FOLDER_NAME

module.exports = {
    BD_NAME,
    DB_URI,
    CORS_ORIGINE,
    PORT,
    CLOUDINARY_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_FOLDER_NAME
}